### ISSUE TITLE
What's going on here?

### ISSUE THREAD

**Issue by LappleApple** [zalando-incubator/paintshop#1]
Wondering if the org repo is the best place for this -- LMK your thoughts!

**Comment by LappleApple** [comment]
I made this repo public and transferred to the Incubator.

**Comment by retnuh** [comment]
I don't think we want this public; we don't want candidates we give the
Paintshop test to to be able to easily find solutions!

Hunter

**Comment by LappleApple** [comment]
@retnuh This is the first time I've heard of the repo being *actively* used in interviews. I'd asked previously for someone to move it to GHE and got no response.

**Comment by retnuh** [comment]
@LappleApple the _repo_ isn't used in interviews, the problem that the repo has _solutions_ for is.
If you can make this private again, I'll clone a copy and push it up to GHE this week.

**Comment by LappleApple** [comment]
@retnuh Yes, I understand that the solutions are in here and that the repo itself isn't used. I'll move back to the main org, and you can clone and reserve in GHE.
